# Generated by Django 4.2.7 on 2025-06-14 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("skills_extracted", models.JSONField(blank=True, default=list)),
                ("experience_years", models.IntegerField(blank=True, null=True)),
                ("education_details", models.JSONField(blank=True, default=list)),
                ("job_titles", models.JSONField(blank=True, default=list)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("last_analyzed", models.DateTimeField(blank=True, null=True)),
                ("analysis_version", models.CharField(default="1.0", max_length=10)),
                (
                    "student",
                    models.OneToOneField(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resumes",
            },
        ),
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.IntegerField(default=0)),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                ("suggestions", models.JSONField(default=list)),
                ("content_quality_score", models.IntegerField(default=0)),
                ("formatting_score", models.IntegerField(default=0)),
                ("keywords_score", models.IntegerField(default=0)),
                ("experience_relevance_score", models.IntegerField(default=0)),
                ("recommended_roles", models.JSONField(default=list)),
                ("skill_gaps", models.JSONField(default=list)),
                (
                    "market_relevance",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_analysis",
            },
        ),
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("content", models.TextField()),
                ("file_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("changes_summary", models.TextField(blank=True)),
                ("improvement_score", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_versions",
                "ordering": ["-version_number"],
                "unique_together": {("resume", "version_number")},
            },
        ),
    ]
