# Generated by Django 4.2.7 on 2025-07-11 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('skills_extracted', models.JSONField(blank=True, default=list)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('education_details', models.JSONField(blank=True, default=list)),
                ('job_titles', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('analysis_version', models.CharField(default='1.0', max_length=10)),
            ],
            options={
                'db_table': 'resumes',
                'ordering': ['-updated_date', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('overall_score', models.IntegerField(default=0)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('content_quality_score', models.IntegerField(default=0)),
                ('formatting_score', models.IntegerField(default=0)),
                ('keywords_score', models.IntegerField(default=0)),
                ('experience_relevance_score', models.IntegerField(default=0)),
                ('recommended_roles', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('market_relevance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resume_analysis',
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.IntegerField()),
                ('content', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changes_summary', models.TextField(blank=True)),
                ('improvement_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resume_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
