# Generated by Django 4.2.7 on 2025-06-14 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resume",
            options={"ordering": ["-updated_date", "-upload_date"]},
        ),
    ]
