# Generated by Django 4.2.7 on 2025-06-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0002_alter_resume_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resume",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
