services:
  redis:
    image: redis:6-alpine
    container_name: talentlens_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: talentlens_backend_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_volume_dev:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./config/local.env
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data_dev:
  media_volume_dev:
