# Generated by Django 4.2.7 on 2025-07-11 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('interview_reminder', 'Interview Reminder'), ('resume_uploaded', 'Resume Uploaded'), ('resume_analyzed', 'Resume Analyzed'), ('student_assigned', 'Student Assigned'), ('feedback_available', 'Feedback Available'), ('system_announcement', 'System Announcement')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_interview_reminders', models.BooleanField(default=True)),
                ('email_feedback_available', models.BooleanField(default=True)),
                ('email_system_announcements', models.BooleanField(default=True)),
                ('app_interview_updates', models.BooleanField(default=True)),
                ('app_resume_updates', models.BooleanField(default=True)),
                ('app_feedback_updates', models.BooleanField(default=True)),
                ('reminder_frequency_hours', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('interview_reminder', 'Interview Reminder'), ('resume_uploaded', 'Resume Uploaded'), ('resume_analyzed', 'Resume Analyzed'), ('student_assigned', 'Student Assigned'), ('feedback_available', 'Feedback Available'), ('system_announcement', 'System Announcement')], max_length=30)),
                ('subject_template', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('available_variables', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
    ]
