# Generated by Django 4.2.7 on 2025-06-14 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("question_order", models.IntegerField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("expected_duration_minutes", models.IntegerField(default=5)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "interview_questions",
                "ordering": ["question_order"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("communication", "Communication"),
                            ("aptitude", "Aptitude"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=60)),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("tab_switches", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                ("is_secure_mode", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interview_sessions",
                "ordering": ["-scheduled_datetime"],
            },
        ),
        migrations.CreateModel(
            name="InterviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField()),
                ("score", models.IntegerField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                ("time_taken_seconds", models.IntegerField(blank=True, null=True)),
                ("relevance_score", models.IntegerField(blank=True, null=True)),
                ("completeness_score", models.IntegerField(blank=True, null=True)),
                ("clarity_score", models.IntegerField(blank=True, null=True)),
                ("example_score", models.IntegerField(blank=True, null=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="interviews.interviewquestion",
                    ),
                ),
            ],
            options={
                "db_table": "interview_responses",
            },
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="interviews.interviewsession",
            ),
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.IntegerField()),
                ("strengths", models.JSONField(default=list)),
                ("areas_for_improvement", models.JSONField(default=list)),
                ("detailed_feedback", models.TextField()),
                ("recommendations", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("technical_score", models.IntegerField(blank=True, null=True)),
                ("communication_score", models.IntegerField(blank=True, null=True)),
                ("problem_solving_score", models.IntegerField(blank=True, null=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "interview_feedback",
            },
        ),
        migrations.CreateModel(
            name="InterviewAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions", models.IntegerField()),
                ("questions_answered", models.IntegerField()),
                ("average_response_time", models.FloatField()),
                ("completion_percentage", models.FloatField()),
                (
                    "performance_trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("declining", "Declining"),
                            ("stable", "Stable"),
                        ],
                        default="stable",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "interview_analytics",
            },
        ),
        migrations.AlterUniqueTogether(
            name="interviewquestion",
            unique_together={("session", "question_order")},
        ),
    ]
