# Generated by Django 4.2.7 on 2025-06-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="is_session_valid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="security_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="security_violations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="session_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
