# Generated by Django 4.2.7 on 2025-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_is_session_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='evaluation_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='expected_answer_length',
            field=models.CharField(choices=[('short', 'Short (1-2 sentences)'), ('medium', 'Medium (1-2 paragraphs)'), ('long', 'Long (3+ paragraphs)')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='time_limit',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='audio_recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='evaluation_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='response_quality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='transcription_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='actual_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='evaluation_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='expected_answer_length',
            field=models.CharField(choices=[('short', 'Short (1-2 sentences)'), ('medium', 'Medium (1-2 paragraphs)'), ('long', 'Long (3+ paragraphs)')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='security_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='time_limit',
            field=models.IntegerField(default=300),
        ),
    ]
