# Generated by Django 4.2.7 on 2025-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interviewquestion_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated')], default='scheduled', max_length=20),
        ),
    ]
