# Generated by Django 4.2.7 on 2025-07-11 19:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_users', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_teachers', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('total_interviews', models.IntegerField(default=0)),
                ('interviews_today', models.IntegerField(default=0)),
                ('completed_interviews', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_resumes', models.IntegerField(default=0)),
                ('resumes_uploaded_today', models.IntegerField(default=0)),
                ('average_resume_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dashboard_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_interviews', models.IntegerField(default=0)),
                ('completed_interviews', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('technical_average', models.FloatField(default=0.0)),
                ('communication_average', models.FloatField(default=0.0)),
                ('aptitude_average', models.FloatField(default=0.0)),
                ('score_trend', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('improvement_percentage', models.FloatField(default=0.0)),
                ('last_interview_date', models.DateTimeField(blank=True, null=True)),
                ('streak_days', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_progress',
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], max_length=10)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('target_roles', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_dismiss_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('total_interviews_conducted', models.IntegerField(default=0)),
                ('interviews_this_month', models.IntegerField(default=0)),
                ('average_student_score', models.FloatField(default=0.0)),
                ('feedback_completion_rate', models.FloatField(default=0.0)),
                ('student_improvement_rate', models.FloatField(default=0.0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_stats',
            },
        ),
    ]
