# Generated by Django 4.2.7 on 2025-07-11 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstats',
            name='teacher',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='target_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetrics',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student',)},
        ),
    ]
