# Generated by Django 4.2.7 on 2025-06-14 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacherstudentmapping",
            options={"ordering": ["-assigned_date"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["first_name", "last_name", "username"]},
        ),
    ]
