# Generated by Django 4.2.7 on 2025-07-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_premium",
            field=models.BooleanField(
                default=False, help_text="Premium users can add unlimited students"
            ),
        ),
    ]
